setwd("/Users/kailiu/Box Sync/Data_Science/Exploratory_Data_Analysis/ExData_Plotting1")
Power <- read.csv("household_power_consumption.txt", header=T, sep = ";", stringsAsFactors = F)
Power$Date2 <- as.Date(as.character(Power$Date), format = "%d/%m/%Y")
newdata <- subset(Power, Date2 == as.Date("2007-02-02") | Date2 == as.Date("2007-02-01"), select = c(Date, Time, Global_active_power, Voltage, Sub_metering_1, Sub_metering_2, Sub_metering_3, Global_reactive_power))
newdata$DateTime <- strptime(paste(newdata$Date, newdata$Time), "%d/%m/%Y %H:%M:%S")
par(mfrow = c(2,2))
plot(newdata$DateTime, newdata$Global_active_power, type = "l", ylab = "Global Active Power (kilowatts)", xlab = "")
plot(newdata$DateTime, newdata$Voltage, type = "l", ylab = "Voltage", xlab = "datetime")
plot(newdata$DateTime, newdata$Sub_metering_1, type = "n", ylab = "Energy sub metering", xlab = "")
lines(newdata$DateTime, newdata$Sub_metering_1, col = "black")
lines(newdata$DateTime, newdata$Sub_metering_2, col = "red")
lines(newdata$DateTime, newdata$Sub_metering_3, col = "blue")
legend("topright", bty = "n", lwd = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(newdata$DateTime, newdata$Global_reactive_power, type = "l", ylab = "Global_reactive_power", xlab = "datetime")
dev.copy(png, file = "plot4.png")
dev.off()