setwd("/Users/kailiu/Box Sync/Data_Science/Exploratory_Data_Analysis/ExData_Plotting1")
Power <- read.csv("household_power_consumption.txt", header=T, sep = ";", stringsAsFactors = F)
Power$Date2 <- as.Date(as.character(Power$Date), format = "%d/%m/%Y")
newdata <- subset(Power, Date2 == as.Date("2007-02-02") | Date2 == as.Date("2007-02-01"), select = c(Date2, Global_active_power))
x <- as.numeric(newdata$Global_active_power)
hist(x, col = "red", main = "Global Active Power", xlab = "Global Active Power (kilowatts)", ylab = "Frequency")
dev.copy(png, file = "plot1.png")
dev.off()